"""empty message

Revision ID: 03297e68ae5e
Revises: 4c6440251d22
Create Date: 2022-06-04 10:24:17.900262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03297e68ae5e'
down_revision = '4c6440251d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_image_link', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
