"""empty message

Revision ID: 04d6ec262720
Revises: d750e65e3a78
Create Date: 2022-06-03 02:23:00.725069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d6ec262720'
down_revision = 'd750e65e3a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_image_link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'artist_image_link')
    # ### end Alembic commands ###
