"""empty message

Revision ID: 0c72a42a0fc9
Revises: dd5d8ac06a29
Create Date: 2022-06-05 15:12:22.829977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c72a42a0fc9'
down_revision = 'dd5d8ac06a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
