"""empty message

Revision ID: 218369ebd4bf
Revises: 5ae36e20f4a4
Create Date: 2022-06-03 02:44:13.613361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218369ebd4bf'
down_revision = '5ae36e20f4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
