"""empty message

Revision ID: 304341d2ac22
Revises: 9a532dc67199
Create Date: 2022-06-03 03:58:07.886774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304341d2ac22'
down_revision = '9a532dc67199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String(120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
