"""empty message

Revision ID: 3c8ed72493fe
Revises: a77c604130a8
Create Date: 2022-06-04 01:20:38.983286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8ed72493fe'
down_revision = 'a77c604130a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'show', 'artist', ['artist_image_link'], ['image_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    # ### end Alembic commands ###
