"""empty message

Revision ID: 40cfa3f56669
Revises: 218369ebd4bf
Create Date: 2022-06-03 03:55:12.119256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40cfa3f56669'
down_revision = '218369ebd4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'past_shows')
    op.drop_column('artist', 'upcoming_shows')
    op.drop_column('show', 'venue_name')
    op.drop_column('show', 'artist_name')
    op.drop_column('venue', 'past_shows')
    op.drop_column('venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('upcoming_shows', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('past_shows', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('venue_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
