"""empty message

Revision ID: 5ae36e20f4a4
Revises: 04d6ec262720
Create Date: 2022-06-03 02:43:42.358798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae36e20f4a4'
down_revision = '04d6ec262720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
