"""empty message

Revision ID: 63380c90db1f
Revises: 0c72a42a0fc9
Create Date: 2022-06-05 15:14:41.162044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63380c90db1f'
down_revision = '0c72a42a0fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
