"""empty message

Revision ID: 78b4e669fd85
Revises: cb428d2b583c
Create Date: 2022-06-03 01:28:09.547436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b4e669fd85'
down_revision = 'cb428d2b583c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('artist', sa.Column('past_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('past_shows', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'past_shows')
    op.drop_column('venue', 'upcoming_shows')
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'upcoming_shows')
    op.drop_column('artist', 'past_shows')
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
