"""empty message

Revision ID: a9e2b244fefe
Revises: 9efa56533fd4
Create Date: 2022-06-02 23:03:24.347139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e2b244fefe'
down_revision = '9efa56533fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=200), nullable=True))
    op.add_column('artist', sa.Column('past_shows', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.add_column('show', sa.Column('venue_name', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('past_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'past_shows')
    op.drop_column('venue', 'upcoming_shows')
    op.drop_column('show', 'venue_name')
    op.drop_column('show', 'venue_id')
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'past_shows_count')
    op.drop_column('artist', 'past_shows')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
