"""empty message

Revision ID: c8c85a2486ac
Revises: 07ba6b6196a4
Create Date: 2022-06-02 14:53:46.510801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c85a2486ac'
down_revision = '07ba6b6196a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('artist_name', sa.String(length=120), nullable=True),
    sa.Column('artist_image_link', sa.String(length=120), nullable=True),
    sa.Column('start_time', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###
