"""empty message

Revision ID: cb428d2b583c
Revises: a9e2b244fefe
Create Date: 2022-06-03 01:26:23.620296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb428d2b583c'
down_revision = 'a9e2b244fefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'past_shows')
    op.drop_column('artist', 'genres')
    op.drop_column('artist', 'past_shows_count')
    op.drop_column('venue', 'past_shows')
    op.drop_column('venue', 'upcoming_shows')
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('past_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
